spring.application.name=Drive
spring.datasource.url=jdbc:postgresql://localhost:5432/driving
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
jwt.secret=R0VORVJBVEVEX1BFRkVDVEVEX1NFRUNSRVQxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
jwt.expiration=3600000